In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('test_df.csv')

In [3]:
df

,Date,Date.1,Close,Volume,Close_AUDUSD,Close_USDCAD,Close_USDCHF,AUDUSD_Returns,USDCAD_Returns,USDCHF_Returns,...,realGDPPerCapita,retailMoneyFunds,retailSales,Returns,Returns_100,upper_barrier,lower_barrier,touch_upper,touch_lower,label
0,2010-01-03 19:39:00,2010-01-03 19:39:00,1.43064,93.0,0.89676,1.04778,1.03557,-0.000210,-0.000210,-0.000210,...,53683.0,784.7,308229.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,2010-01-03 21:13:00,2010-01-03 21:13:00,1.42858,144.0,0.89636,1.04723,1.03764,0.000014,0.000014,0.000014,...,53683.0,784.7,308229.0,-0.001440,-0.143992,NaN,NaN,NaN,NaN,0.0
2,2010-01-04 00:44:00,2010-01-04 00:44:00,1.43046,63.0,0.89819,1.04523,1.03570,0.000147,0.000147,0.000147,...,53683.0,784.7,308229.0,0.001316,0.131599,NaN,NaN,NaN,NaN,0.0
3,2010-01-04 02:35:00,2010-01-04 02:35:00,1.42779,146.0,0.89875,1.04832,1.04127,0.000526,0.000526,0.000526,...,53683.0,784.7,308229.0,-0.001867,-0.186653,NaN,NaN,NaN,NaN,0.0
4,2010-01-04 03:39:00,2010-01-04 03:39:00,1.43190,115.0,0.90244,1.04383,1.03790,0.000168,0.000168,0.000168,...,53683.0,784.7,308229.0,0.002879,0.287857,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88249,2024-01-03 15:09:00,2024-01-03 15:09:00,1.09196,182.0,0.67275,1.25931,0.94559,0.000027,0.000027,0.000027,...,67702.0,1674.9,601921.0,0.000862,0.086158,1.093616,1.090304,NaN,NaN,NaN
88250,2024-01-03 16:25:00,2024-01-03 16:25:00,1.09220,107.0,0.67280,1.25931,0.94559,0.000064,0.000064,0.000064,...,67702.0,1674.9,601921.0,0.000220,0.021979,1.093866,1.090534,NaN,NaN,NaN
88251,2024-01-03 19:30:00,2024-01-03 19:30:00,1.09250,77.0,0.67310,1.25931,0.94559,0.000000,0.000000,0.000000,...,67702.0,1674.9,601921.0,0.000275,0.027467,1.094176,1.090824,NaN,NaN,NaN
88252,2024-01-03 21:19:00,2024-01-03 21:19:00,1.09175,53.0,0.67262,1.25931,0.94559,0.000000,0.000000,0.000000,...,67702.0,1674.9,601921.0,-0.000686,-0.068650,1.093447,1.090053,NaN,NaN,NaN
88253,2024-01-03 23:30:00,2024-01-03 23:30:00,1.09255,73.0,0.67374,1.25931,0.94559,0.000073,0.000073,0.000073,...,67702.0,1674.9,601921.0,0.000733,0.073277,1.094205,1.090895,NaN,NaN,NaN

In [4]:
df =df.dropna()

In [5]:
df

,Date,Date.1,Close,Volume,Close_AUDUSD,Close_USDCAD,Close_USDCHF,AUDUSD_Returns,USDCAD_Returns,USDCHF_Returns,...,realGDPPerCapita,retailMoneyFunds,retailSales,Returns,Returns_100,upper_barrier,lower_barrier,touch_upper,touch_lower,label
20,2010-01-05 04:25:00,2010-01-05 04:25:00,1.44281,63.0,0.91394,1.03742,1.02941,0.000028,0.000028,0.000028,...,53683.0,784.7,308229.0,0.000707,0.070745,1.447798,1.437822,2010-01-10 22:25:00,2010-01-05 14:18:00,-1.0
21,2010-01-05 05:47:00,2010-01-05 05:47:00,1.44255,52.0,0.91499,1.03776,1.02915,-0.000125,-0.000125,-0.000125,...,53683.0,784.7,308229.0,-0.000180,-0.018020,1.447394,1.437706,2010-01-10 22:25:00,2010-01-05 14:18:00,-1.0
22,2010-01-05 07:13:00,2010-01-05 07:13:00,1.44222,39.0,0.91459,1.03554,1.03013,-0.000062,-0.000062,-0.000062,...,53683.0,784.7,308229.0,-0.000229,-0.022876,1.447050,1.437390,2010-01-10 18:50:00,2010-01-05 14:18:00,-1.0
23,2010-01-05 08:30:00,2010-01-05 08:30:00,1.44332,67.0,0.91595,1.03574,1.02914,-0.000028,-0.000028,-0.000028,...,53683.0,784.7,308229.0,0.000763,0.076271,1.447902,1.438738,2010-01-10 22:25:00,2010-01-05 13:04:00,-1.0
24,2010-01-05 09:20:00,2010-01-05 09:20:00,1.44165,152.0,0.91245,1.03795,1.03106,0.000055,0.000055,0.000055,...,53683.0,784.7,308229.0,-0.001157,-0.115705,1.446062,1.437238,2010-01-10 18:50:00,2010-01-05 14:18:00,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88174,2023-12-27 14:11:00,2023-12-27 14:11:00,1.10989,169.0,0.68374,1.25931,0.94559,-0.000171,-0.000171,-0.000171,...,67702.0,1674.9,601921.0,-0.000468,-0.046830,1.111636,1.108144,2023-12-28 03:02:00,2023-12-28 11:31:00,1.0
88175,2023-12-27 15:27:00,2023-12-27 15:27:00,1.11040,93.0,0.68434,1.25931,0.94559,0.000063,0.000063,0.000063,...,67702.0,1674.9,601921.0,0.000460,0.045950,1.112088,1.108712,2023-12-28 05:00:00,2023-12-28 11:31:00,1.0
88176,2023-12-27 17:05:00,2023-12-27 17:05:00,1.11035,24.0,0.68450,1.25931,0.94559,-0.000225,-0.000225,-0.000225,...,67702.0,1674.9,601921.0,-0.000045,-0.004503,1.112048,1.108652,2023-12-28 05:00:00,2023-12-28 11:31:00,1.0
88179,2023-12-28 00:00:00,2023-12-28 00:00:00,1.11104,122.0,0.68424,1.25931,0.94559,0.000009,0.000009,0.000009,...,67702.0,1674.9,601921.0,-0.000522,-0.052176,1.112841,1.109239,2023-12-28 06:07:00,2023-12-28 09:15:00,1.0
88201,2023-12-29 05:02:00,2023-12-29 05:02:00,1.10519,148.0,0.68050,1.25931,0.94559,0.000054,0.000054,0.000054,...,67702.0,1674.9,601921.0,-0.000850,-0.084981,1.107635,1.102745,2023-12-29 07:27:00,2024-01-01 21:54:00,1.0

In [8]:
count = df[df['label'] == -1.0]['label'].count()

In [9]:
count

40046

In [10]:
count = df[df['label'] == 1.0]['label'].count()

In [11]:
count

41135